### ISSUE TITLE
St19 doesn't have CCT control and other issues

### ISSUE THREAD

**Issue by muddro1** [toxuin/hass-AiDot#3]
First thank you so much for updating this. Having 2 issues with this.

First, after integrating, I get this error: Failed to perform the action light/turn_off. 'AidotLight' object has no attribute 'lanCtrl'.

Also seeing this in the logs:None (<class 'custom_components.aidot.light.AidotLight'>) sets invalid supported color modes {<ColorMode.ONOFF: 'onoff'>, <ColorMode.BRIGHTNESS: 'brightness'>}, this will stop working in Home Assistant Core 2025.3, please report it to the author of the 'aidot' custom integration

The second issue is I think related to the above message which is I cannot adjust the CCT white temperature.

**Comment by toxuin** [comment]
I must admit - I don't own any AiDot-compatible lights. I just ordered some - will investigate. This looks like a refactoring problem, but I need some devices to test on to verify it actually works.
Thanks for reporting!

**Comment by toxuin** [comment]
After comparing the original (pre-refactoring) code with the new code, there seems to be no need for `lanCtrl.sendDevAttr` anymore - it now happens in `deviceClient` itself. I've published a release with that change - please let me know if that works or does not, since I cannot test it with the actual bulbs just yet.

**Comment by muddro1** [comment]
The first error no longer shows up. Thank you. Much more stable for turning on and off. The second error and the inability to modify color temp remains but so happy that you are helping with this!

Happy to contribute so you can get a test device.

**Comment by toxuin** [comment]
@muddro1 can you please check if the [latest release](https://github.com/toxuin/hass-AiDot/releases) allows you to control CCT of your bulbs?
The config schema has changed, so most likely you'll need to delete and re-add the integration.

I couldn't get the exact light as you have quickly, so I got some Linkind matter-compatible RGBW ones - I figured that if all the bells and whistles on *those* work - CCT-only lights should work as well. Let me know if that is the case! 😄

**Comment by muddro1** [comment]
Fails to load the integration:
```

Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 11:36:16 AM (2 occurrences)
Last logged: 11:41:33 AM

Error setting up entry Zach.malamud@gmail.com My Home for aidot
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aidot/__init__.py", line 32, in async_setup_entry
    hass.data.setdefault(DOMAIN, {})[CONF_DEVICE_LIST] = entry.data[CONF_DEVICE_LIST]
                                                         ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'device_list'
```

**Comment by toxuin** [comment]
Have you removed the integration, then re-added it, or is it right after the update + restart?

**Comment by muddro1** [comment]
This fixed it! Thank you very much for your work uplifting this repo!

**Comment by SeongGino** [comment]
Should this issue be closed now since it's been resolved in a release?
